
import { emptyApiSlice } from "./apiSlice";

// Define a function to get the token from localStorage

export const blogApi = emptyApiSlice.injectEndpoints({
  
  endpoints: (builder) => ({
    getAllBlogs: builder.query({
      query: () => "/",
      providesTags: ["Blogs"],
    }),
    createBlog: builder.mutation({
      query: (blog) => ({
        url: "/blogs",
        method: "POST",
        body: blog,
      }),
      invalidatesTags: ["Blogs"],
    }),
    deleteBlog: builder.mutation({
      query: (id) => ({
        url: `/blogs/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Blogs"],
    }),
  }),
});

// Export the hooks generated by the rtk query
export const {
  useGetAllBlogsQuery,
  useCreateBlogMutation,
  useDeleteBlogMutation,
} = blogApi;
